package compiler

import (
	rt "effra.local/prototype/runtime/effra"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

type goEmitter struct {
	next     int
	bindings map[string]Binding
	program  *Program
}

func goType(t string) string {
	if strings.HasPrefix(t, "GoResult:") {
		return "er.GoResult[" + goType(strings.TrimPrefix(t, "GoResult:")) + "]"
	}
	switch t {
	case "string":
		return "string"
	case "Handler":
		return "func(string) efEffect[string]"
	case "bool":
		return "bool"
	case "i64":
		return "int64"
	case "bytes":
		return "[]byte"
	case "File":
		return "*er.File"
	default:
		if strings.HasPrefix(t, "provider:") {
			return "efService_" + goIdent(strings.TrimPrefix(t, "provider:"))
		}
		if strings.HasPrefix(t, "Fiber:") {
			return "*er.Fiber[" + goType(strings.TrimPrefix(t, "Fiber:")) + "]"
		}
		if strings.HasPrefix(t, "GoResult:") {
			return "er.GoResult[" + goType(strings.TrimPrefix(t, "GoResult:")) + "]"
		}
		if t == "()" || t == "never" || t == "invalid" || t == "" {
			return "struct{}"
		}
		return "efType_" + goIdent(t)
	}
}
func goIdent(name string) string {
	name = strings.ReplaceAll(strings.ReplaceAll(name, ".", "_"), ":", "_")
	if name == "" {
		return "Anonymous"
	}
	return name
}
func goFieldName(name string) string {
	// Prefix every source field with its byte length and a generated namespace.
	// Initial-capital lowering alone maps names such as `id` and `Id` to the
	// same Go selector, and `_` would become Go's blank field. Source names are
	// ASCII lexer identifiers, so the length prefix plus goIdent is injective.
	return "EfField_" + strconv.Itoa(len(name)) + "_" + goIdent(name)
}
func goVariantType(typeName, variantName string) string {
	// Encode both qualified components with their source lengths. A plain
	// concatenation makes enum AB.C collide with enum A.BC (and names that
	// contain underscores), which would make otherwise checked programs fail
	// during Go compilation.
	return "efTypeV_" + strconv.Itoa(len(typeName)) + "_" + goIdent(typeName) + "_" + strconv.Itoa(len(variantName)) + "_" + goIdent(variantName)
}
func goParams(f *Function) string {
	parts := []string{}
	for _, p := range f.Params {
		parts = append(parts, "efLocal_"+p.Name+" "+goType(p.Type))
	}
	return strings.Join(parts, ", ")
}
func goArgs(f *Function) string {
	parts := []string{}
	for _, p := range f.Params {
		parts = append(parts, "efLocal_"+p.Name)
	}
	return strings.Join(parts, ", ")
}
func goMethodType(f *Function) string {
	types := []string{}
	for _, p := range f.Params {
		types = append(types, goType(p.Type))
	}
	return "func(" + strings.Join(types, ", ") + ") efEffect[" + goType(f.Return) + "]"
}
func (g *goEmitter) temp() string { g.next++; return fmt.Sprintf("efTemp%d", g.next) }

// EmitGo lowers checked IR to a standalone Go program using the managed runtime.
// Error and requirement rows are checked in the frontend; success values stay typed in Go.
func (r *Result) EmitGo() (string, error) { return r.emitGo(nil) }
func (r *Result) emitGo(tests []*Symbol) (string, error) {
	if tests == nil {
		if err := r.Entry(); err != nil {
			return "", err
		}
	}
	g := &goEmitter{program: r.Program}
	var out strings.Builder
	out.WriteString("// Generated by the Effra prototype. Source revision: " + r.Revision + "\npackage main\nimport (\"fmt\"; \"os\"; \"context\"; \"os/signal\"; \"syscall\"; er \"effra.generated/runtime\"\n")
	if tests != nil {
		out.WriteString("\"encoding/json\"\n")
	}
	for _, imp := range r.Program.Imports {
		if r.Program.UsedImports[imp.Alias] {
			out.WriteString("efGo_" + imp.Alias + " " + strconv.Quote(imp.Path) + "\n")
		}
	}
	out.WriteString(")\n")
	g.bindings = r.Program.Bindings
	out.WriteString(`
type efExit[A any] = er.Exit[A]
type efEffect[A any] func(efContext) efExit[A]
func efToRuntime[A any](ctx efContext,program efEffect[A]) er.Effect[A] {return func(fc *er.FiberContext) er.Exit[A] {ctx.Runtime=fc;return program(ctx)}}
func efFromRuntime[A any](program er.Effect[A]) efEffect[A] {return func(ctx efContext)efExit[A]{return er.Invoke(ctx.Runtime,program)}}
func efCatch[A any](program efEffect[A],tag string,fallback func()A)efEffect[A]{return func(ctx efContext)efExit[A]{return er.Invoke(ctx.Runtime,er.Catch(efToRuntime(ctx,program),tag,fallback))}}
func efScoped[A any](program efEffect[A])efEffect[A]{return func(ctx efContext)efExit[A]{return er.Invoke(ctx.Runtime,er.Scoped(efToRuntime(ctx,program)))}}
func efTimeout[A any](program efEffect[A],duration int64)efEffect[A]{return func(ctx efContext)efExit[A]{return er.Invoke(ctx.Runtime,er.Timeout(efToRuntime(ctx,program),duration))}}
func efFork[A any](program efEffect[A])efEffect[*er.Fiber[A]]{return func(ctx efContext)efExit[*er.Fiber[A]]{return er.Invoke(ctx.Runtime,er.Fork(efToRuntime(ctx,program)))}}
func efJoin[A any](fiber *er.Fiber[A])efEffect[A]{return efFromRuntime(fiber.Join())}
func efInterrupt[A any](fiber *er.Fiber[A])efEffect[struct{}]{return efFromRuntime(fiber.Interrupt())}
func efCancel[A any](fiber *er.Fiber[A])efEffect[struct{}]{return efFromRuntime(func(*er.FiberContext)er.Exit[struct{}]{fiber.Cancel();return er.Succeed(struct{}{})})}
`)
	g.dataTypes(&out)
	services := append(builtins(), r.Program.Services...)
	out.WriteString("type efContext struct {\nRuntime *er.FiberContext\n")
	for _, s := range services {
		out.WriteString("s_" + s.Name + " *efService_" + s.Name + "\n")
	}
	out.WriteString("}\n")
	for _, s := range services {
		out.WriteString("type efService_" + s.Name + " struct {\n")
		for _, m := range s.Methods {
			out.WriteString("m_" + m.Name + " " + goMethodType(m) + "\n")
		}
		out.WriteString("}\n")
		out.WriteString("func efProvide_" + s.Name + "[A any](program efEffect[A], provider efService_" + s.Name + ") efEffect[A] { return func(ctx efContext) efExit[A] { ctx.s_" + s.Name + " = &provider; return program(ctx) } }\n")
		for _, m := range s.Methods {
			out.WriteString("func efCall_" + s.Name + "_" + m.Name + "(" + goParams(m) + ") efEffect[" + goType(m.Return) + "] { return func(ctx efContext) efExit[" + goType(m.Return) + "] {\n")
			out.WriteString("if ctx.s_" + s.Name + " == nil || ctx.s_" + s.Name + ".m_" + m.Name + " == nil { return efExit[" + goType(m.Return) + "]{Defect:fmt.Errorf(" + strconv.Quote("missing provider "+s.Name+"."+m.Name) + ")} }\n")
			out.WriteString("return ctx.s_" + s.Name + ".m_" + m.Name + "(" + goArgs(m) + ")(ctx)\n} }\n")
		}
	}
	out.WriteString(`
func efProvider_Assertions()efService_Assert{return efService_Assert{m_check:func(condition bool,message string)efEffect[struct{}]{return efFromRuntime(func(*er.FiberContext)er.Exit[struct{}]{if !condition{return er.Fail[struct{}]("AssertionFailed",message)};return er.Succeed(struct{}{})})},m_equalText:func(actual,expected string)efEffect[struct{}]{return efFromRuntime(func(*er.FiberContext)er.Exit[struct{}]{if actual!=expected{return er.Fail[struct{}]("AssertionFailed",fmt.Sprintf("expected %q; received %q",expected,actual))};return er.Succeed(struct{}{})})}}}
func efProvider_Stdout()efService_Console{return efService_Console{m_log:func(message string)efEffect[struct{}]{return efFromRuntime(er.Println(message))}}}
func efProvider_LiveClock()efService_Clock{return efService_Clock{m_sleep:func(ms int64)efEffect[struct{}]{return efFromRuntime(er.Sleep(ms))}}}
func efProvider_LiveFiles()efService_Files{return efService_Files{m_openRead:func(path string)efEffect[*er.File]{return efFromRuntime(er.OpenRead(path))},m_readText:func(file *er.File)efEffect[string]{return efFromRuntime(er.ReadText(file))},m_readFile:func(path string)efEffect[string]{return efFromRuntime(er.ReadFile(path))}}}
func efProvider_LiveEnv()efService_Env{return efService_Env{m_get:func(name string)efEffect[string]{return efFromRuntime(er.Env(name))}}}
func efProvider_RuntimeLive()efService_Runtime{return efService_Runtime{m_inspect:func()efEffect[string]{return efFromRuntime(er.InspectScope())}}}
func efProvider_Host()efService_Foreign{return efService_Foreign{}}
func efProvider_GoHttp()efService_Http{return efService_Http{m_serve:func(address string,handler func(string)efEffect[string])efEffect[struct{}]{return func(ctx efContext)efExit[struct{}]{return er.Invoke(ctx.Runtime,er.ServeHTTP(address,func(path string)er.Effect[string]{return efToRuntime(ctx,handler(path))},func(bound string){fmt.Println("listening http://"+bound)}))}}}}
`)
	for _, p := range r.Program.Providers {
		out.WriteString("func efProvider_" + p.Name + "() efService_" + p.Service + " { return efService_" + p.Service + "{\n")
		for _, m := range p.Methods {
			out.WriteString("m_" + m.Name + ": " + strings.TrimSpace(g.function(m)) + ",\n")
		}
		out.WriteString("} }\n")
	}
	for _, f := range r.Program.Functions {
		ret := goType(f.Return)
		if f.Effect {
			ret = "efEffect[" + ret + "]"
		}
		out.WriteString("func efFunction_" + f.Name + "(" + goParams(f) + ") " + ret + " {\n")
		if f.Effect {
			out.WriteString("return func(ctx efContext) efExit[" + goType(f.Return) + "] {\nif err:=ctx.Runtime.Checkpoint();err!=nil{return er.Interrupt[" + goType(f.Return) + "](err)}\n")
		}
		out.WriteString(g.block(f.Body, f.Effect, f.Return))
		if f.Effect {
			out.WriteString("}\n")
		}
		out.WriteString("}\n")
	}
	if tests == nil {
		out.WriteString("func main() { base,stop:=signal.NotifyContext(context.Background(),os.Interrupt,syscall.SIGTERM);defer stop();exit:=er.RunContext(base,func(fc *er.FiberContext) er.Exit[" + goType(r.Find("main").Contract.Success) + "]{return efFunction_main()(efContext{Runtime:fc})});if exit.IsFailure(){fmt.Fprintln(os.Stderr,exit.Cause());os.Exit(1)}\n")
		if r.Find("main").Contract.Success != "()" {
			out.WriteString("fmt.Println(exit.Value)\n")
		}
		out.WriteString("}\n")
	} else {
		out.WriteString(`func main(){base,stop:=signal.NotifyContext(context.Background(),os.Interrupt,syscall.SIGTERM);defer stop();type testResult struct{Name string ` + "`json:\"name\"`" + `;Passed bool ` + "`json:\"passed\"`" + `;Cause string ` + "`json:\"cause,omitempty\"`" + `;Reasons []map[string]string ` + "`json:\"reasons,omitempty\"`" + `};results:=[]testResult{};passed:=true;assertions:=efProvider_Assertions();`)
		for _, test := range tests {
			out.WriteString("{exit:=er.RunContext(base,func(fc *er.FiberContext)er.Exit[struct{}]{return efFunction_" + test.Name + "()(efContext{Runtime:fc,s_Assert:&assertions})});item:=testResult{Name:" + strconv.Quote(test.Name) + ",Passed:!exit.IsFailure()};if exit.IsFailure(){item.Cause=fmt.Sprint(exit.Cause());for _,reason:=range exit.Cause(){detail:=map[string]string{\"kind\":reason.Kind};if reason.Failure!=nil{detail[\"tag\"]=reason.Failure.Tag;if reason.Failure.Payload!=nil{detail[\"message\"]=fmt.Sprint(reason.Failure.Payload)}}else if reason.Err!=nil{detail[\"message\"]=reason.Err.Error()};item.Reasons=append(item.Reasons,detail)};passed=false};results=append(results,item)}\n")
		}
		out.WriteString(`json.NewEncoder(os.Stdout).Encode(map[string]any{"schemaVersion":1,"passed":passed,"tests":results});if !passed{os.Exit(1)}}`)
	}
	formatted, err := format.Source([]byte(out.String()))
	if err != nil {
		return "", fmt.Errorf("Go lowering generated invalid syntax: %w", err)
	}
	return string(formatted), nil
}
func (g *goEmitter) function(f *Function) string {
	ret := goType(f.Return)
	if f.Effect {
		ret = "efEffect[" + ret + "]"
	}
	open := "func(" + goParams(f) + ") " + ret + " {\n"
	close := "}\n"
	if f.Effect {
		open += "return func(ctx efContext) efExit[" + goType(f.Return) + "] {\nif err:=ctx.Runtime.Checkpoint();err!=nil{return er.Interrupt[" + goType(f.Return) + "](err)}\n"
		close = "}\n}\n"
	}
	return open + g.block(f.Body, f.Effect, f.Return) + close
}
func (g *goEmitter) failed(name, ret string) string {
	return "if " + name + ".IsFailure(){return er.Propagate[" + goType(ret) + "](" + name + ")}\n"
}
func (g *goEmitter) block(b *Block, effect bool, ret string) string {
	var out strings.Builder
	finish := func(expr string) {
		if effect {
			out.WriteString("return efExit[" + goType(ret) + "]{Value:" + expr + "}\n")
		} else {
			out.WriteString("return " + expr + "\n")
		}
	}
	if len(b.Statements) == 0 {
		finish("struct{}{}")
		return out.String()
	}
	for i, s := range b.Statements {
		if s.Kind == "fail" {
			payload := g.failurePayload(s.Name, s.Payload, effect, ret, &out)
			out.WriteString("return efExit[" + goType(ret) + "]{Failure:&er.Failure{Tag:" + strconv.Quote(s.Name) + ",Payload:" + payload + "}}\n")
			continue
		}
		expr := g.expr(s.Value, effect, ret, &out)
		if s.Kind == "let" {
			out.WriteString("efLocal_" + s.Name + " := " + expr + "\n_ = efLocal_" + s.Name + "\n")
			if i == len(b.Statements)-1 {
				finish("struct{}{}")
			}
		} else if i == len(b.Statements)-1 {
			if s.Value.Type.Success == "never" {
				out.WriteString("_ = " + expr + "\nreturn efExit[" + goType(ret) + "]{Defect:fmt.Errorf(\"bottom expression unexpectedly succeeded\")}\n")
			} else {
				finish(expr)
			}
		} else {
			out.WriteString("_ = " + expr + "\n")
		}
	}
	return out.String()
}
func (g *goEmitter) expr(e *Expr, effect bool, ret string, out *strings.Builder) string {
	switch e.Kind {
	case "member":
		left := g.expr(e.Left, effect, ret, out)
		if e.Text == "field" {
			return left + "." + goFieldName(e.Name)
		}
		if e.Name == "hasError" {
			return "(" + left + ".Err != nil)"
		}
		return left + ".Value"
	case "orFail":
		left := g.expr(e.Left, effect, ret, out)
		return "func(ctx efContext)efExit[" + goType(e.Type.Success) + "]{return er.Invoke(ctx.Runtime,er.OrFail(efToRuntime(ctx," + left + ")))}"
	case "integer":
		return "int64(" + e.Text + ")"
	case "string":
		return strconv.Quote(e.Text)
	case "bool":
		return e.Text
	case "unit":
		return "struct{}{}"
	case "construct":
		return g.construct(e, effect, ret, out)
	case "name":
		if e.Text == "handler" {
			return "efFunction_" + e.Name
		}
		if e.Text == "provider" {
			return "efProvider_" + e.Name + "()"
		}
		return "efLocal_" + e.Name
	case "scope":
		name := g.temp()
		out.WriteString(name + " := efScoped(func(ctx efContext)efExit[" + goType(e.Type.Success) + "]{\n" + g.block(e.Then, true, e.Type.Success) + "})(ctx)\n" + g.failed(name, ret))
		return name + ".Value"
	case "fork":
		expr := g.expr(e.Left, effect, ret, out)
		name := g.temp()
		out.WriteString(name + " := efFork(" + expr + ")(ctx)\n" + g.failed(name, ret))
		return name + ".Value"
	case "timeout":
		left := g.expr(e.Left, effect, ret, out)
		name := g.temp()
		out.WriteString(name + " := " + left + "\n")
		right := g.expr(e.Right, effect, ret, out)
		return "efTimeout(" + name + ", " + right + ")"
	case "call":
		if e.Text == "data" {
			return g.constructCall(e, effect, ret, out)
		}
		if e.Text == "foreign" {
			return g.foreign(e, effect, ret, out)
		}
		if e.Text == "fiber" {
			method := map[string]string{"join": "efJoin", "interrupt": "efInterrupt", "cancel": "efCancel"}[e.Left.Name]
			return method + "(efLocal_" + e.Left.Left.Name + ")"
		}
		args := []string{}
		for _, a := range e.Args {
			expr := g.expr(a, effect, ret, out)
			name := g.temp()
			out.WriteString(name + " := " + expr + "\n")
			args = append(args, name)
		}
		if e.Left.Kind == "name" {
			return "efFunction_" + e.Left.Name + "(" + strings.Join(args, ", ") + ")"
		}
		return "efCall_" + e.Left.Left.Name + "_" + e.Left.Name + "(" + strings.Join(args, ", ") + ")"
	case "run":
		expr := g.expr(e.Left, effect, ret, out)
		name := g.temp()
		out.WriteString(name + " := " + expr + "(ctx)\n" + g.failed(name, ret))
		return name + ".Value"
	case "provide":
		left := g.expr(e.Left, effect, ret, out)
		name := g.temp()
		out.WriteString(name + " := " + left + "\n")
		right := g.expr(e.Right, effect, ret, out)
		return "efProvide_" + e.Name + "(" + name + ", " + right + ")"
	case "catch":
		left := g.expr(e.Left, effect, ret, out)
		var fallback strings.Builder
		right := g.expr(e.Right, false, e.Type.Success, &fallback)
		return "efCatch(" + left + ", " + strconv.Quote(e.Name) + ", func() " + goType(e.Type.Success) + " {\n" + fallback.String() + "return " + right + "\n})"
	case "binary":
		left := g.expr(e.Left, effect, ret, out)
		name := g.temp()
		out.WriteString(name + " := " + left + "\n")
		right := g.expr(e.Right, effect, ret, out)
		return "(" + name + " " + e.Name + " " + right + ")"
	case "if":
		var body strings.Builder
		condition := g.expr(e.Left, effect, e.Type.Success, &body)
		body.WriteString("if " + condition + " {\n" + g.block(e.Then, effect, e.Type.Success) + "} else {\n" + g.block(e.Else, effect, e.Type.Success) + "}\n")
		if effect {
			name := g.temp()
			out.WriteString(name + " := func() efExit[" + goType(e.Type.Success) + "] {\n" + body.String() + "}()\n" + g.failed(name, ret))
			return name + ".Value"
		}
		return "func() " + goType(e.Type.Success) + " {\n" + body.String() + "}()"
	case "match":
		return g.match(e, effect, ret, out)
	}
	panic("unchecked expression reached Go emitter")
}

func (g *goEmitter) dataTypes(out *strings.Builder) {
	for _, declaration := range g.programDeclarations() {
		switch declaration.Kind {
		case "record", "error":
			out.WriteString("type efType_" + goIdent(declaration.Name) + " struct {\n")
			for _, field := range declaration.Fields {
				out.WriteString(goFieldName(field.Name) + " " + goType(field.Type) + "\n")
			}
			out.WriteString("}\n")
		case "enum":
			out.WriteString("type efType_" + goIdent(declaration.Name) + " interface { efVariant_" + goIdent(declaration.Name) + "() }\n")
			for _, variant := range declaration.Variants {
				out.WriteString("type " + goVariantType(declaration.Name, variant.Name) + " struct {\n")
				for _, field := range variant.Fields {
					out.WriteString(goFieldName(field.Name) + " " + goType(field.Type) + "\n")
				}
				out.WriteString("}\nfunc (" + goVariantType(declaration.Name, variant.Name) + ") efVariant_" + goIdent(declaration.Name) + "() {}\n")
			}
		}
	}
}
func (g *goEmitter) programDeclarations() []Declaration {
	if g.program == nil {
		return nil
	}
	return g.programDeclarationProjection()
}
func (g *goEmitter) programDeclarationProjection() []Declaration {
	result := []Declaration{}
	for _, decl := range g.program.ErrorDecls {
		result = append(result, Declaration{Kind: "error", Name: decl.Name, Fields: decl.Fields, Span: decl.Span})
	}
	for _, record := range g.program.Records {
		result = append(result, Declaration{Kind: "record", Name: record.Name, Fields: record.Fields, Span: record.Span})
	}
	for _, enum := range g.program.Enums {
		result = append(result, Declaration{Kind: "enum", Name: enum.Name, Variants: enum.Variants, Span: enum.Span})
	}
	return result
}
func (g *goEmitter) declaration(kind, name string) *Declaration {
	for _, declaration := range g.programDeclarations() {
		if declaration.Kind == kind && declaration.Name == name {
			return &declaration
		}
	}
	return nil
}
func (g *goEmitter) failurePayload(name string, payload *Expr, effect bool, ret string, out *strings.Builder) string {
	if payload == nil {
		return "nil"
	}
	decl := g.declaration("error", name)
	if payload.Kind != "payload" {
		expr := g.expr(payload, false, ret, out)
		if decl != nil && len(decl.Fields) == 1 {
			return "efType_" + goIdent(name) + "{" + goFieldName(decl.Fields[0].Name) + ":" + expr + "}"
		}
		return expr
	}
	parts := []string{}
	for _, field := range payload.Fields {
		parts = append(parts, goFieldName(field.Name)+":"+g.expr(field.Value, false, ret, out))
	}
	return "efType_" + goIdent(name) + "{" + strings.Join(parts, ",") + "}"
}
func (g *goEmitter) construct(e *Expr, effect bool, ret string, out *strings.Builder) string {
	typeName, variantName := "", ""
	if e.Left != nil && e.Left.Kind == "name" {
		typeName = e.Left.Name
	} else if e.Left != nil && e.Left.Kind == "member" && e.Left.Left.Kind == "name" {
		typeName, variantName = e.Left.Left.Name, e.Left.Name
	}
	parts := []string{}
	for _, field := range e.Fields {
		parts = append(parts, goFieldName(field.Name)+":"+g.expr(field.Value, false, ret, out))
	}
	if variantName != "" {
		variant := goVariantType(typeName, variantName) + "{" + strings.Join(parts, ",") + "}"
		return "efType_" + goIdent(typeName) + "(" + variant + ")"
	}
	return "efType_" + goIdent(typeName) + "{" + strings.Join(parts, ",") + "}"
}
func (g *goEmitter) constructCall(e *Expr, effect bool, ret string, out *strings.Builder) string {
	return g.construct(&Expr{Kind: "construct", Left: e.Left, Fields: e.Fields, Type: e.Type}, effect, ret, out)
}
func (g *goEmitter) match(e *Expr, effect bool, ret string, out *strings.Builder) string {
	value := g.expr(e.Left, effect, ret, out)
	resultType := goType(e.Type.Success)
	variant := g.temp()
	var body strings.Builder
	body.WriteString(variant + " := " + value + "\n")
	if effect {
		body.WriteString("switch efMatch := " + variant + ".(type) {\n")
		for _, arm := range e.Arms {
			body.WriteString("case " + goVariantType(arm.Pattern.TypeName, arm.Pattern.VariantName) + ":\n")
			body.WriteString("_ = efMatch\n")
			for _, field := range sortedBindingNames(arm.Pattern.Bindings) {
				binding := arm.Pattern.Bindings[field]
				if binding != "_" {
					body.WriteString("efLocal_" + binding + " := efMatch." + goFieldName(field) + "\n_ = efLocal_" + binding + "\n")
				}
			}
			body.WriteString(g.block(arm.Body, true, e.Type.Success))
		}
		body.WriteString("default: return efExit[" + resultType + "]{Defect:fmt.Errorf(\"unreachable non-exhaustive match\")}\n}\n")
		name := g.temp()
		out.WriteString(name + " := func() efExit[" + resultType + "] {\n" + body.String() + "}()\n" + g.failed(name, ret))
		return name + ".Value"
	}
	body.WriteString("switch efMatch := " + variant + ".(type) {\n")
	for _, arm := range e.Arms {
		body.WriteString("case " + goVariantType(arm.Pattern.TypeName, arm.Pattern.VariantName) + ":\n")
		body.WriteString("_ = efMatch\n")
		for _, field := range sortedBindingNames(arm.Pattern.Bindings) {
			binding := arm.Pattern.Bindings[field]
			if binding != "_" {
				body.WriteString("efLocal_" + binding + " := efMatch." + goFieldName(field) + "\n_ = efLocal_" + binding + "\n")
			}
		}
		body.WriteString(g.block(arm.Body, false, e.Type.Success))
	}
	body.WriteString("default: panic(\"unreachable non-exhaustive match\")\n}\n")
	return "func() " + resultType + " {\n" + body.String() + "}()"
}

// WriteRuntime writes only changed source bytes so Go's own build cache remains useful.
func WriteRuntime(directory string) error {
	path := filepath.Join(directory, "runtime")
	if err := os.MkdirAll(path, 0755); err != nil {
		return err
	}
	for name, data := range rt.Sources() {
		file := filepath.Join(path, name)
		old, _ := os.ReadFile(file)
		if string(old) == string(data) {
			continue
		}
		if err := os.WriteFile(file, data, 0644); err != nil {
			return err
		}
	}
	return nil
}

func (g *goEmitter) foreign(e *Expr, effect bool, ret string, out *strings.Builder) string {
	b := g.bindings[e.Name]
	args := []string{}
	if b.Context {
		args = append(args, "fc.Context()")
	}
	for _, arg := range e.Args {
		expr := g.expr(arg, effect, ret, out)
		temp := g.temp()
		out.WriteString(temp + " := " + expr + "\n")
		args = append(args, temp)
	}
	call := "efGo_" + e.Name + "(" + strings.Join(args, ",") + ")"
	result := goType(e.Type.Success)
	body := "return er.Succeed(" + call + ")"
	if b.Return == "()" {
		body = call + ";return er.Succeed(struct{}{})"
	}
	if b.HasError {
		if b.Return == "()" {
			body = "nativeErr := " + call + ";return er.Succeed(er.GoResult[struct{}]{Value:struct{}{},Err:nativeErr})"
		} else {
			body = "nativeValue,nativeErr := " + call + ";return er.Succeed(er.GoResult[" + goType(b.Return) + "]{Value:nativeValue,Err:nativeErr})"
		}
	}
	return "func(ctx efContext)efExit[" + result + "]{if ctx.s_Foreign==nil{return er.Die[" + result + "](fmt.Errorf(\"missing Foreign provider\"))};return er.Invoke(ctx.Runtime,func(fc *er.FiberContext)er.Exit[" + result + "]{" + body + "})}"
}
