package compiler

import (
	"encoding/json"
	"fmt"
	"strings"
)

func quoted(s string) string { b, _ := json.Marshal(s); return string(b) }
func jsValueType(t string) string {
	switch t {
	case "()":
		return "void"
	case "bool":
		return "boolean"
	default:
		return "string"
	}
}
func jsContract(f *Function) string {
	success := jsValueType(f.Return)
	if !f.Effect {
		return success
	}
	errors := []string{}
	for _, n := range normalized(f.Errors) {
		errors = append(errors, "{ readonly _tag: "+quoted(n)+" }")
	}
	err := "never"
	if len(errors) > 0 {
		err = strings.Join(errors, " | ")
	}
	services := []string{}
	for _, n := range normalized(f.Services) {
		services = append(services, n+"Requirement")
	}
	requirements := "never"
	if len(services) > 0 {
		requirements = strings.Join(services, " | ")
	}
	return "Effect.Effect<" + success + ", " + err + ", " + requirements + ">"
}

// Emit consumes only checked compiler IR. JavaScript is never used as a type-checking oracle.
func (r *Result) Emit(entry bool) (string, string, error) {
	if !r.Checked {
		return "", "", fmt.Errorf("refusing to emit source with diagnostics")
	}
	if entry {
		if err := r.Entry(); err != nil {
			return "", "", err
		}
	}
	var out, decl strings.Builder
	out.WriteString("// Generated by the Effra prototype. Source revision: " + r.Revision + "\nimport { Context, Effect } from 'effect';\n")
	out.WriteString("const __ef_service_Console = Context.Service('effra/prototype/Console');\nconst __ef_provider_Stdout = { log: (message) => Effect.sync(() => console.log(message)) };\nconst __ef_call = (service, method, args) => Effect.flatMap(service, provider => provider[method](...args));\n")
	decl.WriteString("import type { Context, Effect } from 'effect';\n")
	console := &Service{Name: "Console", Methods: []*Function{{Name: "log", Params: []Param{{Name: "message", Type: "string"}}, Return: "()", Effect: true}}}
	allServices := append([]*Service{console}, r.Program.Services...)
	for _, s := range allServices {
		decl.WriteString("export interface " + s.Name + "Requirement { readonly _effraService: " + quoted(s.Name) + " }\n")
		out.WriteString("export { __ef_service_" + s.Name + " as " + s.Name + " };\n")
		decl.WriteString("declare const __ef_service_" + s.Name + ": Context.Service<" + s.Name + "Requirement, " + jsShape(s.Methods) + ">;\nexport { __ef_service_" + s.Name + " as " + s.Name + " };\n")
	}
	for _, s := range r.Program.Services {
		out.WriteString("const __ef_service_" + s.Name + " = Context.Service(" + quoted("effra/prototype/"+s.Name) + ");\n")
	}
	for _, p := range r.Program.Providers {
		out.WriteString("const __ef_provider_" + p.Name + " = {\n")
		for _, f := range p.Methods {
			out.WriteString("[" + quoted(f.Name) + "]: " + jsFunction(f) + ",\n")
		}
		out.WriteString("};\n")
	}
	out.WriteString("export { __ef_provider_Stdout as Stdout };\n")
	decl.WriteString("declare const __ef_provider_Stdout: " + jsShape(console.Methods) + ";\nexport { __ef_provider_Stdout as Stdout };\n")
	for _, p := range r.Program.Providers {
		out.WriteString("export { __ef_provider_" + p.Name + " as " + p.Name + " };\n")
		decl.WriteString("declare const __ef_provider_" + p.Name + ": " + jsShape(p.Methods) + ";\nexport { __ef_provider_" + p.Name + " as " + p.Name + " };\n")
	}
	for _, f := range r.Program.Functions {
		out.WriteString("const __ef_function_" + f.Name + " = " + jsFunction(f) + ";\nexport { __ef_function_" + f.Name + " as " + f.Name + " };\n")
		params := []string{}
		for _, p := range f.Params {
			params = append(params, "arg_"+p.Name+": "+jsValueType(p.Type))
		}
		decl.WriteString("declare const __ef_function_" + f.Name + ": (" + strings.Join(params, ", ") + ") => " + jsContract(f) + ";\nexport { __ef_function_" + f.Name + " as " + f.Name + " };\n")
	}
	if entry {
		out.WriteString("Effect.runPromise(__ef_function_main()).then(value => { if (value !== undefined) console.log(value); }, error => { console.error(error); process.exitCode = 1; });\n")
	}
	return out.String(), decl.String(), nil
}
func jsFunction(f *Function) string {
	params := []string{}
	for _, p := range f.Params {
		params = append(params, "__ef_local_"+p.Name)
	}
	open, close := "{", "}"
	if f.Effect {
		open = "Effect.gen(function* () {"
		close = "})"
	}
	return "(" + strings.Join(params, ", ") + ") => " + open + "\n" + jsBlock(f.Body, f.Effect) + close
}
func jsBlock(b *Block, effect bool) string {
	var out strings.Builder
	if len(b.Statements) == 0 {
		return "return undefined;\n"
	}
	for i, s := range b.Statements {
		switch s.Kind {
		case "let":
			out.WriteString("const __ef_local_" + s.Name + " = " + jsExpr(s.Value, effect) + ";\n")
			if i == len(b.Statements)-1 {
				out.WriteString("return undefined;\n")
			}
		case "fail":
			out.WriteString("return yield* Effect.fail({ _tag: " + quoted(s.Name) + " });\n")
		default:
			if i == len(b.Statements)-1 {
				out.WriteString("return ")
			}
			out.WriteString(jsExpr(s.Value, effect) + ";\n")
		}
	}
	return out.String()
}
func jsExpr(e *Expr, effect bool) string {
	switch e.Kind {
	case "string":
		return quoted(e.Text)
	case "bool":
		return e.Text
	case "unit":
		return "undefined"
	case "name":
		if e.Text == "provider" {
			return "__ef_provider_" + e.Name
		}
		return "__ef_local_" + e.Name
	case "call":
		args := []string{}
		for _, a := range e.Args {
			args = append(args, jsExpr(a, effect))
		}
		if e.Left.Kind == "name" {
			return "__ef_function_" + e.Left.Name + "(" + strings.Join(args, ", ") + ")"
		}
		return "__ef_call(__ef_service_" + e.Left.Left.Name + ", " + quoted(e.Left.Name) + ", [" + strings.Join(args, ", ") + "])"
	case "run":
		return "(yield* " + jsExpr(e.Left, effect) + ")"
	case "provide":
		return "Effect.provideService(" + jsExpr(e.Left, effect) + ", __ef_service_" + e.Name + ", " + jsExpr(e.Right, effect) + ")"
	case "catch":
		return "Effect.catchTag(" + jsExpr(e.Left, effect) + ", " + quoted(e.Name) + ", () => Effect.succeed(" + jsExpr(e.Right, false) + "))"
	case "binary":
		op := e.Name
		if op == "==" {
			op = "==="
		}
		return "(" + jsExpr(e.Left, effect) + " " + op + " " + jsExpr(e.Right, effect) + ")"
	case "if":
		body := "if (" + jsExpr(e.Left, effect) + ") {\n" + jsBlock(e.Then, effect) + "} else {\n" + jsBlock(e.Else, effect) + "}\n"
		if effect {
			return "(yield* Effect.gen(function* () {\n" + body + "}))"
		}
		return "(() => {\n" + body + "})()"
	}
	panic("unchecked expression reached emitter")
}

func jsShape(methods []*Function) string {
	out := "{ "
	for _, f := range methods {
		params := []string{}
		for _, p := range f.Params {
			params = append(params, "arg_"+p.Name+": "+jsValueType(p.Type))
		}
		out += "readonly " + quoted(f.Name) + ": (" + strings.Join(params, ", ") + ") => " + jsContract(f) + "; "
	}
	return out + "}"
}
