package compiler

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"strings"
)

//go:embed lifecycle.mjs
var lifecycleJS string

func quoted(s string) string { b, _ := json.Marshal(s); return string(b) }
func jsValueType(t string) string {
	switch t {
	case "()":
		return "void"
	case "bool":
		return "boolean"
	case "i64":
		return "bigint"
	case "bytes":
		return "Uint8Array"
	case "File":
		return "File"
	case "Handler":
		return "(path: string) => Effect.Effect<string, unknown, unknown>"
	case "never", "invalid":
		return "never"
	default:
		if strings.HasPrefix(t, "provider:") {
			return strings.TrimPrefix(t, "provider:") + "Provider"
		}
		if strings.HasPrefix(t, "GoResult:") {
			return "{ readonly value: " + jsValueType(strings.TrimPrefix(t, "GoResult:")) + "; readonly error: Error | undefined }"
		}
		if strings.HasPrefix(t, "Fiber:") {
			return "Fiber.Fiber<" + jsValueType(strings.TrimPrefix(t, "Fiber:")) + ">"
		}
		if strings.ContainsAny(t, ":") {
			return "never"
		}
		return t
	}
}
func jsContract(f *Function) string {
	return jsContractFor(f, nil)
}
func jsContractFor(f *Function, declarations map[string]Declaration) string {
	success := jsValueType(f.Return)
	if !f.Effect {
		return success
	}
	errors := []string{}
	for _, n := range normalized(f.Errors) {
		if declaration, ok := declarations[n]; ok && len(declaration.Fields) > 0 {
			errors = append(errors, n+"Error")
		} else {
			errors = append(errors, "{ readonly _tag: "+quoted(n)+" }")
		}
	}
	err := "never"
	if len(errors) > 0 {
		err = strings.Join(errors, " | ")
	}
	services := []string{}
	for _, n := range normalized(f.Services) {
		services = append(services, n+"Requirement")
	}
	requirements := "never"
	if len(services) > 0 {
		requirements = strings.Join(services, " | ")
	}
	return "Effect.Effect<" + success + ", " + err + ", " + requirements + ">"
}

// Emit consumes only checked compiler IR. JavaScript is never used as a type-checking oracle.
func (r *Result) Emit(entry bool) (string, string, error) {
	if !r.Checked {
		return "", "", fmt.Errorf("refusing to emit source with diagnostics")
	}
	if r.Program.GoOnly {
		return "", "", fmt.Errorf("program uses features currently implemented only for Go")
	}
	if entry {
		if err := r.Entry(); err != nil {
			return "", "", err
		}
	}
	var out, decl strings.Builder
	out.WriteString("// Generated by the Effra prototype. Source revision: " + r.Revision + "\nimport { Context, Effect, Fiber, Scope, Exit, Cause, Option } from 'effect';\n")
	out.WriteString(lifecycleJS)
	out.WriteString("const __ef_service_Console = Context.Service('effra/prototype/Console');\nconst __ef_provider_Stdout = { log: (message) => Effect.sync(() => console.log(message)) };\nconst __ef_call = (service, method, args) => Effect.flatMap(service, provider => provider[method](...args));\n")
	decl.WriteString("import type { Context, Effect, Fiber } from 'effect';\nexport interface File {readonly _effraFile: \"File\"}\n")
	for _, declaration := range r.ProgramDeclarations() {
		switch declaration.Kind {
		case "record":
			decl.WriteString("declare const __ef_brand_" + declaration.Name + ": unique symbol;\n")
			decl.WriteString("export interface " + declaration.Name + " { ")
			decl.WriteString("readonly [__ef_brand_" + declaration.Name + "]: \"" + declaration.Name + "\"; ")
			for _, field := range declaration.Fields {
				decl.WriteString("readonly " + field.Name + ": " + jsValueType(field.Type) + "; ")
			}
			decl.WriteString("}\n")
		case "enum":
			decl.WriteString("declare const __ef_brand_" + declaration.Name + ": unique symbol;\n")
			if len(declaration.Variants) == 0 {
				decl.WriteString("export type " + declaration.Name + " = never;\n")
				break
			}
			decl.WriteString("export type " + declaration.Name + " = ")
			for i, variant := range declaration.Variants {
				if i > 0 {
					decl.WriteString(" | ")
				}
				decl.WriteString("{ readonly [__ef_brand_" + declaration.Name + "]: \"" + declaration.Name + "\"; readonly _tag: " + quoted(declaration.Name+"."+variant.Name))
				for _, field := range variant.Fields {
					decl.WriteString("; readonly " + field.Name + ": " + jsValueType(field.Type))
				}
				decl.WriteString(" }")
			}
			decl.WriteString(";\n")
		case "error":
			decl.WriteString("export interface " + declaration.Name + "Error { readonly _tag: " + quoted(declaration.Name))
			for _, field := range declaration.Fields {
				decl.WriteString("; readonly " + field.Name + ": " + jsValueType(field.Type))
			}
			decl.WriteString(" }\n")
		}
	}
	allServices := append(builtins(), r.Program.Services...)
	for _, s := range allServices {
		decl.WriteString("export interface " + s.Name + "Requirement { readonly _effraService: " + quoted(s.Name) + " }\n")
		out.WriteString("export { __ef_service_" + s.Name + " as " + s.Name + " };\n")
		decl.WriteString("declare const __ef_service_" + s.Name + ": Context.Service<" + s.Name + "Requirement, " + jsShape(s.Methods, declarationMap(r), false) + ">;\nexport { __ef_service_" + s.Name + " as " + s.Name + " };\n")
	}
	for _, s := range allServices {
		if s.Name == "Console" {
			continue
		}
		out.WriteString("const __ef_service_" + s.Name + "=Context.Service(" + quoted("effra/prototype/"+s.Name) + ");\n")
	}
	for _, s := range allServices {
		decl.WriteString("export type " + s.Name + "Provider = " + jsShape(s.Methods, declarationMap(r), false) + ";\n")
	}
	out.WriteString(`
const __ef_provider_Assertions={check:(condition,message)=>condition?Effect.succeed(undefined):Effect.fail({_tag:'AssertionFailed',message}),equalText:(actual,expected)=>actual===expected?Effect.succeed(undefined):Effect.fail({_tag:'AssertionFailed',message:'expected '+JSON.stringify(expected)+'; received '+JSON.stringify(actual)})};
const __ef_provider_LiveClock={sleep:ms=> ms<0n || ms>2147483647n ? Effect.die(new Error('invalid millisecond duration')) : Effect.sleep(Number(ms))};
const __ef_provider_LiveEnv={get:name=>Effect.sync(()=>process.env[name] ?? '')};
`)
	for _, p := range r.Program.Providers {
		if providerConstructed(p) {
			out.WriteString(jsProviderConstructor(p))
			continue
		}
		out.WriteString("const __ef_provider_" + p.Name + " = {\n")
		for _, f := range p.Methods {
			out.WriteString("[" + quoted(f.Name) + "]: " + jsFunction(f) + ",\n")
		}
		out.WriteString("};\n")
	}
	for _, p := range builtinProviders() {
		if p.Service != "Console" && p.Service != "Clock" && p.Service != "Env" && p.Service != "Assert" {
			continue
		}
		out.WriteString("export {__ef_provider_" + p.Name + " as " + p.Name + "};\n")
		for _, s := range allServices {
			if s.Name == p.Service {
				decl.WriteString("declare const __ef_provider_" + p.Name + ": " + jsShape(s.Methods, declarationMap(r), false) + ";\nexport {__ef_provider_" + p.Name + " as " + p.Name + "};\n")
			}
		}
	}
	for _, p := range r.Program.Providers {
		out.WriteString("export { __ef_provider_" + p.Name + " as " + p.Name + " };\n")
		if providerConstructed(p) {
			decl.WriteString("declare const __ef_provider_" + p.Name + ": " + jsConstructorType(p, declarationMap(r)) + ";\nexport { __ef_provider_" + p.Name + " as " + p.Name + " };\n")
		} else {
			decl.WriteString("declare const __ef_provider_" + p.Name + ": " + jsShape(p.Methods, declarationMap(r), true) + ";\nexport { __ef_provider_" + p.Name + " as " + p.Name + " };\n")
		}
	}
	for _, f := range r.Program.Functions {
		out.WriteString("const __ef_function_" + f.Name + " = " + jsFunction(f) + ";\nexport { __ef_function_" + f.Name + " as " + f.Name + " };\n")
		params := []string{}
		for _, p := range f.Params {
			params = append(params, "arg_"+p.Name+": "+jsValueType(p.Type))
		}
		decl.WriteString("declare const __ef_function_" + f.Name + ": (" + strings.Join(params, ", ") + ") => " + jsContractFor(f, declarationMap(r)) + ";\nexport { __ef_function_" + f.Name + " as " + f.Name + " };\n")
	}
	if entry {
		out.WriteString("Effect.runPromise(__ef_function_main()).then(value => { if (value !== undefined) console.log(typeof value === 'bigint' ? value.toString() : value); }, error => { console.error(error); process.exitCode = 1; });\n")
	}
	return out.String(), decl.String(), nil
}

// ProgramDeclarations is a target-independent view used by both emitters.
// Keep this projection on Result so declaration order and identity remain part
// of the checked semantic model rather than being rediscovered by a backend.
func (r *Result) ProgramDeclarations() []Declaration {
	return append([]Declaration{}, r.Declarations...)
}
func jsFunction(f *Function) string {
	params := []string{}
	for _, p := range f.Params {
		params = append(params, "__ef_local_"+p.Name)
	}
	return "(" + strings.Join(params, ", ") + ") => " + jsEffectBody(f)
}
func jsEffectBody(f *Function) string {
	open, close := "{", "}"
	if f.Effect {
		open = "__ef_autoScope(Effect.gen(function* () {"
		close = "}))"
	}
	return open + "\n" + jsBlock(f.Body, f.Effect) + close
}

func jsProviderMethod(f *Function, captures []string) string {
	params := []string{}
	for _, p := range f.Params {
		params = append(params, "__ef_local_"+p.Name)
	}
	effect := jsEffectBody(f)
	for i := len(normalized(captures)) - 1; i >= 0; i-- {
		service := normalized(captures)[i]
		effect = "Effect.provideService(" + effect + ", __ef_service_" + service + ", __ef_capture_" + service + ")"
	}
	return "(" + strings.Join(params, ", ") + ") => " + effect
}

func jsProviderConstructor(p *Provider) string {
	params := []string{}
	for _, param := range p.Params {
		params = append(params, "__ef_local_"+param.Name)
	}
	methods := []string{}
	for _, method := range p.Methods {
		implementation := jsFunction(method)
		if len(p.Services) > 0 {
			implementation = jsProviderMethod(method, p.Services)
		}
		methods = append(methods, "["+quoted(method.Name)+"]: "+implementation)
	}
	body := "Effect.succeed({" + strings.Join(methods, ", ") + "})"
	for i := len(normalized(p.Services)) - 1; i >= 0; i-- {
		service := normalized(p.Services)[i]
		body = "Effect.flatMap(__ef_service_" + service + ", __ef_capture_" + service + " => " + body + ")"
	}
	return "const __ef_provider_" + p.Name + " = (" + strings.Join(params, ", ") + ") => " + body + ";\n"
}

func jsConstructorType(p *Provider, declarations map[string]Declaration) string {
	constructor := &Function{Name: p.Name, Params: p.Params, Return: "provider:" + p.Service, Effect: true, Services: normalized(p.Services)}
	return "(" + jsFunctionParams(p.Params) + ") => " + jsContractFor(constructor, declarations)
}

func jsFunctionParams(params []Param) string {
	parts := []string{}
	for _, p := range params {
		parts = append(parts, "arg_"+p.Name+": "+jsValueType(p.Type))
	}
	return strings.Join(parts, ", ")
}

func jsBlock(b *Block, effect bool) string {
	var out strings.Builder
	if len(b.Statements) == 0 {
		return "return undefined;\n"
	}
	for i, s := range b.Statements {
		switch s.Kind {
		case "let":
			out.WriteString("const __ef_local_" + s.Name + " = " + jsExpr(s.Value, effect) + ";\n")
			if i == len(b.Statements)-1 {
				out.WriteString("return undefined;\n")
			}
		case "fail":
			payload := "{}"
			if s.Payload != nil {
				payload = jsPayload(s.Payload, effect)
			}
			out.WriteString("return yield* Effect.fail({ _tag: " + quoted(s.Name) + ", ..." + payload + " });\n")
		default:
			if i == len(b.Statements)-1 {
				out.WriteString("return ")
			}
			out.WriteString(jsExpr(s.Value, effect) + ";\n")
		}
	}
	return out.String()
}
func jsExpr(e *Expr, effect bool) string {
	switch e.Kind {
	case "member":
		left := jsExpr(e.Left, effect)
		if e.Text == "field" {
			return left + "[" + quoted(e.Name) + "]"
		}
		if e.Name == "hasError" {
			return "(" + left + ".error != null)"
		}
		return left + ".value"
	case "scope":
		return "(yield* __ef_scoped(Effect.gen(function*(){" + jsBlock(e.Then, true) + "})))"
	case "fork":
		return "(yield* __ef_fork(" + jsExpr(e.Left, effect) + "))"
	case "timeout":
		return "__ef_timeout(" + jsExpr(e.Left, effect) + "," + jsExpr(e.Right, effect) + ")"
	case "integer":
		return e.Text + "n"
	case "string":
		return quoted(e.Text)
	case "bool":
		return e.Text
	case "unit":
		return "undefined"
	case "construct":
		return jsConstruct(e, effect)
	case "name":
		if e.Text == "provider" {
			return "__ef_provider_" + e.Name
		}
		return "__ef_local_" + e.Name
	case "call":
		if e.Text == "data" {
			return jsConstructCall(e, effect)
		}
		if e.Text == "fiber" {
			method := e.Left.Name
			if method == "interrupt" {
				return "__ef_interrupt(" + jsExpr(e.Left.Left, effect) + ")"
			}
			if method == "cancel" {
				return "__ef_cancel(" + jsExpr(e.Left.Left, effect) + ")"
			}
			return "__ef_join(" + jsExpr(e.Left.Left, effect) + ")"
		}
		if e.Text == "provider-constructor" {
			args := []string{}
			for _, a := range e.Args {
				args = append(args, jsExpr(a, effect))
			}
			return "__ef_provider_" + e.Left.Name + "(" + strings.Join(args, ", ") + ")"
		}
		args := []string{}
		for _, a := range e.Args {
			args = append(args, jsExpr(a, effect))
		}
		if e.Left.Kind == "name" {
			return "__ef_function_" + e.Left.Name + "(" + strings.Join(args, ", ") + ")"
		}
		return "__ef_call(__ef_service_" + e.Left.Left.Name + ", " + quoted(e.Left.Name) + ", [" + strings.Join(args, ", ") + "])"
	case "run":
		return "(yield* " + jsExpr(e.Left, effect) + ")"
	case "provide":
		return "Effect.provideService(" + jsExpr(e.Left, effect) + ", __ef_service_" + e.Name + ", " + jsExpr(e.Right, effect) + ")"
	case "catch":
		return "__ef_catch(" + jsExpr(e.Left, effect) + ", " + quoted(e.Name) + ", () => (" + jsExpr(e.Right, false) + "))"
	case "binary":
		op := e.Name
		if op == "==" {
			op = "==="
		}
		return "(" + jsExpr(e.Left, effect) + " " + op + " " + jsExpr(e.Right, effect) + ")"
	case "if":
		body := "if (" + jsExpr(e.Left, effect) + ") {\n" + jsBlock(e.Then, effect) + "} else {\n" + jsBlock(e.Else, effect) + "}\n"
		if effect {
			return "(yield* Effect.gen(function* () {\n" + body + "}))"
		}
		return "(() => {\n" + body + "})()"
	case "match":
		return jsMatch(e, effect)
	}
	panic("unchecked expression reached emitter")
}

func jsPayload(e *Expr, effect bool) string {
	if e.Kind != "payload" {
		return "{ value: " + jsExpr(e, effect) + " }"
	}
	parts := []string{}
	for _, field := range e.Fields {
		parts = append(parts, "["+quoted(field.Name)+"]: "+jsExpr(field.Value, false))
	}
	return "{" + strings.Join(parts, ", ") + "}"
}
func jsConstruct(e *Expr, effect bool) string {
	parts := []string{}
	for _, field := range e.Fields {
		parts = append(parts, "["+quoted(field.Name)+"]: "+jsExpr(field.Value, false))
	}
	if e.Left != nil && e.Left.Kind == "member" {
		return "({ _tag: " + quoted(e.Left.Left.Name+"."+e.Left.Name) + ", " + strings.Join(parts, ", ") + " })"
	}
	return "({ " + strings.Join(parts, ", ") + " })"
}
func jsConstructCall(e *Expr, effect bool) string {
	parts := []string{}
	for _, field := range e.Fields {
		parts = append(parts, "["+quoted(field.Name)+"]: "+jsExpr(field.Value, false))
	}
	if e.Left != nil && e.Left.Kind == "member" {
		return "({ _tag: " + quoted(e.Left.Left.Name+"."+e.Left.Name) + ", " + strings.Join(parts, ", ") + " })"
	}
	return "({ " + strings.Join(parts, ", ") + " })"
}
func jsMatch(e *Expr, effect bool) string {
	value := jsExpr(e.Left, effect)
	body := "const __ef_match = " + value + ";\nswitch (__ef_match._tag) {\n"
	for _, arm := range e.Arms {
		body += "case " + quoted(arm.Pattern.TypeName+"."+arm.Pattern.VariantName) + ": {\n"
		for _, field := range sortedBindingNames(arm.Pattern.Bindings) {
			binding := arm.Pattern.Bindings[field]
			if binding != "_" {
				body += "const __ef_local_" + binding + " = __ef_match[" + quoted(field) + "];\n"
			}
		}
		body += jsBlock(arm.Body, effect) + "}\n"
	}
	body += "default: throw new Error(\"unreachable non-exhaustive match\");\n}\n"
	if effect {
		return "(yield* Effect.gen(function* () {\n" + body + "}))"
	}
	return "(() => {\n" + body + "})()"
}

func declarationMap(r *Result) map[string]Declaration {
	result := map[string]Declaration{}
	if r == nil {
		return result
	}
	for _, declaration := range r.Declarations {
		result[declaration.Name] = declaration
	}
	return result
}
func jsShape(methods []*Function, declarations map[string]Declaration, hideServices bool) string {
	out := "{ "
	for _, f := range methods {
		params := []string{}
		for _, p := range f.Params {
			params = append(params, "arg_"+p.Name+": "+jsValueType(p.Type))
		}
		contract := f
		if hideServices {
			copy := *f
			copy.Services = nil
			contract = &copy
		}
		out += "readonly " + quoted(f.Name) + ": (" + strings.Join(params, ", ") + ") => " + jsContractFor(contract, declarations) + "; "
	}
	return out + "}"
}
