package compiler

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"strings"
)

//go:embed lifecycle.mjs
var lifecycleJS string

func quoted(s string) string { b, _ := json.Marshal(s); return string(b) }
func jsValueType(t string) string {
	switch t {
	case "()":
		return "void"
	case "bool":
		return "boolean"
	case "i64":
		return "bigint"
	case "bytes":
		return "Uint8Array"
	case "File":
		return "File"
	case "Latch":
		return "Latch"
	case "Handler":
		return "(path: string) => Effect.Effect<string, unknown, unknown>"
	default:
		return "string"
	}
}
func jsContract(f *Function) string {
	success := jsValueType(f.Return)
	if !f.Effect {
		return success
	}
	errors := []string{}
	for _, n := range normalized(f.Errors) {
		errors = append(errors, "{ readonly _tag: "+quoted(n)+" }")
	}
	err := "never"
	if len(errors) > 0 {
		err = strings.Join(errors, " | ")
	}
	services := []string{}
	for _, n := range normalized(f.Services) {
		services = append(services, n+"Requirement")
	}
	requirements := "never"
	if len(services) > 0 {
		requirements = strings.Join(services, " | ")
	}
	return "Effect.Effect<" + success + ", " + err + ", " + requirements + ">"
}

// Emit consumes only checked compiler IR. JavaScript is never used as a type-checking oracle.
func (r *Result) Emit(entry bool) (string, string, error) {
	if !r.Checked {
		return "", "", fmt.Errorf("refusing to emit source with diagnostics")
	}
	if r.Program.GoOnly {
		return "", "", fmt.Errorf("program uses features currently implemented only for Go")
	}
	if entry {
		if err := r.Entry(); err != nil {
			return "", "", err
		}
	}
	var out, decl strings.Builder
	out.WriteString("// Generated by the Effra prototype. Source revision: " + r.Revision + "\nimport { Context, Clock, Duration, Effect, Fiber, Scope, Scheduler, Exit, Cause, Option } from 'effect';\n")
	out.WriteString(lifecycleJS)
	out.WriteString("const __ef_service_Console = Context.Service('effra/prototype/Console');\nconst __ef_provider_Stdout = { log: (message) => Effect.sync(() => console.log(message)) };\nconst __ef_call = (service, method, args) => Effect.flatMap(service, provider => provider[method](...args));\n")
	decl.WriteString("import type { Context, Effect } from 'effect';\nexport interface File {readonly _effraFile: \"File\"}\nexport interface Latch {readonly _effraLatch: \"Latch\"}\n")
	allServices := append(builtins(), r.Program.Services...)
	for _, s := range allServices {
		decl.WriteString("export interface " + s.Name + "Requirement { readonly _effraService: " + quoted(s.Name) + " }\n")
		out.WriteString("export { __ef_service_" + s.Name + " as " + s.Name + " };\n")
		decl.WriteString("declare const __ef_service_" + s.Name + ": Context.Service<" + s.Name + "Requirement, " + jsShape(s.Methods) + ">;\nexport { __ef_service_" + s.Name + " as " + s.Name + " };\n")
	}
	for _, s := range allServices {
		if s.Name == "Console" {
			continue
		}
		out.WriteString("const __ef_service_" + s.Name + "=Context.Service(" + quoted("effra/prototype/"+s.Name) + ");\n")
	}
	out.WriteString(`
const __ef_provider_Assertions={check:(condition,message)=>condition?Effect.succeed(undefined):Effect.fail({_tag:'AssertionFailed',message}),equalText:(actual,expected)=>actual===expected?Effect.succeed(undefined):Effect.fail({_tag:'AssertionFailed',message:'expected '+JSON.stringify(expected)+'; received '+JSON.stringify(actual)})};
const __ef_provider_LiveClock={sleep:ms=> ms<0n || ms>2147483647n ? Effect.die(new Error('invalid millisecond duration')) : Effect.callback((resume,signal)=>{const timer=setTimeout(()=>resume(Effect.succeed(undefined)),Number(ms));const abort=()=>{clearTimeout(timer);resume(Effect.interrupt);};signal.addEventListener('abort',abort,{once:true});return Effect.sync(()=>{clearTimeout(timer);signal.removeEventListener('abort',abort);});})};
const __ef_provider_TestClock={sleep:()=>Effect.die(new Error('test clock requires the ef test harness'))};
const __ef_provider_LiveEnv={get:name=>Effect.sync(()=>process.env[name] ?? '')};
const __ef_provider_LiveScheduler={sleep:ms=>__ef_provider_LiveClock.sleep(ms),advance:()=>Effect.die(new Error('live scheduler cannot advance')),awaitRegistration:()=>Effect.die(new Error('live scheduler has no registration barrier'))};
const __ef_provider_TestScheduler={sleep:()=>Effect.die(new Error('test scheduler requires the ef test harness')),advance:()=>Effect.die(new Error('test scheduler adjustment is only available in ef test harness')),awaitRegistration:()=>Effect.die(new Error('test scheduler registration barrier is only available in ef test harness'))};
class __ef_latch {
  constructor(){this.done=false;this.waiters=new Set();}
  await(){return Effect.callback((resume,signal)=>{if(this.done){resume(Effect.succeed(undefined));return;}const waiter={resume};this.waiters.add(waiter);const abort=()=>this.waiters.delete(waiter);signal.addEventListener('abort',abort,{once:true});return Effect.sync(()=>{this.waiters.delete(waiter);signal.removeEventListener('abort',abort);});});}
  signal(){return Effect.sync(()=>{if(this.done)return;this.done=true;const waiters=[...this.waiters];this.waiters.clear();for(const waiter of waiters)waiter.resume(Effect.succeed(undefined));});}
}
const __ef_provider_TestSync={latch:()=>Effect.sync(()=>new __ef_latch()),await:latch=>latch?.await?.()??Effect.die(new Error('invalid latch handle')),signal:latch=>latch?.signal?.()??Effect.die(new Error('invalid latch handle'))};
`)
	for _, p := range r.Program.Providers {
		out.WriteString("const __ef_provider_" + p.Name + " = {\n")
		for _, f := range p.Methods {
			out.WriteString("[" + quoted(f.Name) + "]: " + jsFunction(f) + ",\n")
		}
		out.WriteString("};\n")
	}
	for _, p := range builtinProviders() {
		if p.Service != "Console" && p.Service != "Clock" && p.Service != "Env" && p.Service != "Assert" && p.Service != "Scheduler" && p.Service != "Sync" {
			continue
		}
		out.WriteString("export {__ef_provider_" + p.Name + " as " + p.Name + "};\n")
		for _, s := range allServices {
			if s.Name == p.Service {
				decl.WriteString("declare const __ef_provider_" + p.Name + ": " + jsShape(s.Methods) + ";\nexport {__ef_provider_" + p.Name + " as " + p.Name + "};\n")
			}
		}
	}
	for _, p := range r.Program.Providers {
		out.WriteString("export { __ef_provider_" + p.Name + " as " + p.Name + " };\n")
		decl.WriteString("declare const __ef_provider_" + p.Name + ": " + jsShape(p.Methods) + ";\nexport { __ef_provider_" + p.Name + " as " + p.Name + " };\n")
	}
	for _, f := range r.Program.Functions {
		out.WriteString("const __ef_function_" + f.Name + " = " + jsFunction(f) + ";\nexport { __ef_function_" + f.Name + " as " + f.Name + " };\n")
		params := []string{}
		for _, p := range f.Params {
			params = append(params, "arg_"+p.Name+": "+jsValueType(p.Type))
		}
		decl.WriteString("declare const __ef_function_" + f.Name + ": (" + strings.Join(params, ", ") + ") => " + jsContract(f) + ";\nexport { __ef_function_" + f.Name + " as " + f.Name + " };\n")
	}
	if entry {
		out.WriteString("Effect.runPromise(__ef_function_main()).then(value => { if (value !== undefined) console.log(typeof value === 'bigint' ? value.toString() : value); }, error => { console.error(error); process.exitCode = 1; });\n")
	}
	return out.String(), decl.String(), nil
}
func jsFunction(f *Function) string {
	params := []string{}
	for _, p := range f.Params {
		params = append(params, "__ef_local_"+p.Name)
	}
	open, close := "{", "}"
	if f.Effect {
		open = "__ef_autoScope(Effect.gen(function* () {"
		close = "}))"
	}
	return "(" + strings.Join(params, ", ") + ") => " + open + "\n" + jsBlock(f.Body, f.Effect) + close
}
func jsBlock(b *Block, effect bool) string {
	var out strings.Builder
	if len(b.Statements) == 0 {
		return "return undefined;\n"
	}
	for i, s := range b.Statements {
		switch s.Kind {
		case "let":
			out.WriteString("const __ef_local_" + s.Name + " = " + jsExpr(s.Value, effect) + ";\n")
			if i == len(b.Statements)-1 {
				out.WriteString("return undefined;\n")
			}
		case "fail":
			out.WriteString("return yield* Effect.fail({ _tag: " + quoted(s.Name) + " });\n")
		default:
			if i == len(b.Statements)-1 {
				out.WriteString("return ")
			}
			out.WriteString(jsExpr(s.Value, effect) + ";\n")
		}
	}
	return out.String()
}
func jsExpr(e *Expr, effect bool) string {
	switch e.Kind {
	case "scope":
		return "(yield* __ef_scoped(Effect.gen(function*(){" + jsBlock(e.Then, true) + "})))"
	case "fork":
		return "(yield* __ef_fork(" + jsExpr(e.Left, effect) + "))"
	case "timeout":
		return "__ef_timeout(" + jsExpr(e.Left, effect) + "," + jsExpr(e.Right, effect) + ")"
	case "integer":
		return e.Text + "n"
	case "string":
		return quoted(e.Text)
	case "bool":
		return e.Text
	case "unit":
		return "undefined"
	case "name":
		if e.Text == "provider" {
			return "__ef_provider_" + e.Name
		}
		return "__ef_local_" + e.Name
	case "call":
		if e.Text == "fiber" {
			method := e.Left.Name
			if method == "interrupt" {
				return "__ef_interrupt(" + jsExpr(e.Left.Left, effect) + ")"
			}
			if method == "cancel" {
				return "__ef_cancel(" + jsExpr(e.Left.Left, effect) + ")"
			}
			return "__ef_join(" + jsExpr(e.Left.Left, effect) + ")"
		}
		args := []string{}
		for _, a := range e.Args {
			args = append(args, jsExpr(a, effect))
		}
		if e.Left.Kind == "name" {
			return "__ef_function_" + e.Left.Name + "(" + strings.Join(args, ", ") + ")"
		}
		return "__ef_call(__ef_service_" + e.Left.Left.Name + ", " + quoted(e.Left.Name) + ", [" + strings.Join(args, ", ") + "])"
	case "run":
		return "(yield* " + jsExpr(e.Left, effect) + ")"
	case "provide":
		return "Effect.provideService(" + jsExpr(e.Left, effect) + ", __ef_service_" + e.Name + ", " + jsExpr(e.Right, effect) + ")"
	case "catch":
		return "__ef_catch(" + jsExpr(e.Left, effect) + ", " + quoted(e.Name) + ", () => (" + jsExpr(e.Right, false) + "))"
	case "binary":
		op := e.Name
		if op == "==" {
			op = "==="
		}
		return "(" + jsExpr(e.Left, effect) + " " + op + " " + jsExpr(e.Right, effect) + ")"
	case "if":
		body := "if (" + jsExpr(e.Left, effect) + ") {\n" + jsBlock(e.Then, effect) + "} else {\n" + jsBlock(e.Else, effect) + "}\n"
		if effect {
			return "(yield* Effect.gen(function* () {\n" + body + "}))"
		}
		return "(() => {\n" + body + "})()"
	}
	panic("unchecked expression reached emitter")
}

func jsShape(methods []*Function) string {
	out := "{ "
	for _, f := range methods {
		params := []string{}
		for _, p := range f.Params {
			params = append(params, "arg_"+p.Name+": "+jsValueType(p.Type))
		}
		out += "readonly " + quoted(f.Name) + ": (" + strings.Join(params, ", ") + ") => " + jsContract(f) + "; "
	}
	return out + "}"
}
