package compiler

import (
	"fmt"
	"go/format"
	"strconv"
	"strings"
)

type goEmitter struct{ next int }

func goType(t string) string {
	switch t {
	case "string":
		return "string"
	case "bool":
		return "bool"
	default:
		return "struct{}"
	}
}
func goParams(f *Function) string {
	parts := []string{}
	for _, p := range f.Params {
		parts = append(parts, "efLocal_"+p.Name+" "+goType(p.Type))
	}
	return strings.Join(parts, ", ")
}
func goArgs(f *Function) string {
	parts := []string{}
	for _, p := range f.Params {
		parts = append(parts, "efLocal_"+p.Name)
	}
	return strings.Join(parts, ", ")
}
func goMethodType(f *Function) string {
	types := []string{}
	for _, p := range f.Params {
		types = append(types, goType(p.Type))
	}
	return "func(" + strings.Join(types, ", ") + ") efEffect[" + goType(f.Return) + "]"
}
func (g *goEmitter) temp() string { g.next++; return fmt.Sprintf("efTemp%d", g.next) }

// EmitGo lowers checked, portable sequential IR to a standalone Go program.
// Error and requirement rows are checked in the frontend; success values stay typed in Go.
func (r *Result) EmitGo() (string, error) {
	if err := r.Entry(); err != nil {
		return "", err
	}
	g := &goEmitter{}
	var out strings.Builder
	out.WriteString("// Generated by the Effra prototype. Source revision: " + r.Revision + "\npackage main\nimport (\"fmt\"; \"os\")\n")
	out.WriteString(`
type efFailure struct { tag string }
type efExit[A any] struct { value A; failure *efFailure; defect error }
type efEffect[A any] func(efContext) efExit[A]
func efCatch[A any](program efEffect[A], tag string, fallback func() A) efEffect[A] {
 return func(ctx efContext) efExit[A] {
  exit := program(ctx)
  if exit.failure != nil && exit.failure.tag == tag { return efExit[A]{value: fallback()} }
  return exit
 }
}
`)
	console := &Service{Name: "Console", Methods: []*Function{{Name: "log", Params: []Param{{Name: "message", Type: "string"}}, Return: "()", Effect: true}}}
	services := append([]*Service{console}, r.Program.Services...)
	out.WriteString("type efContext struct {\n")
	for _, s := range services {
		out.WriteString("s_" + s.Name + " *efService_" + s.Name + "\n")
	}
	out.WriteString("}\n")
	for _, s := range services {
		out.WriteString("type efService_" + s.Name + " struct {\n")
		for _, m := range s.Methods {
			out.WriteString("m_" + m.Name + " " + goMethodType(m) + "\n")
		}
		out.WriteString("}\n")
		out.WriteString("func efProvide_" + s.Name + "[A any](program efEffect[A], provider efService_" + s.Name + ") efEffect[A] { return func(ctx efContext) efExit[A] { ctx.s_" + s.Name + " = &provider; return program(ctx) } }\n")
		for _, m := range s.Methods {
			out.WriteString("func efCall_" + s.Name + "_" + m.Name + "(" + goParams(m) + ") efEffect[" + goType(m.Return) + "] { return func(ctx efContext) efExit[" + goType(m.Return) + "] {\n")
			out.WriteString("if ctx.s_" + s.Name + " == nil || ctx.s_" + s.Name + ".m_" + m.Name + " == nil { return efExit[" + goType(m.Return) + "]{defect:fmt.Errorf(" + strconv.Quote("missing provider "+s.Name+"."+m.Name) + ")} }\n")
			out.WriteString("return ctx.s_" + s.Name + ".m_" + m.Name + "(" + goArgs(m) + ")(ctx)\n} }\n")
		}
	}
	out.WriteString("func efProvider_Stdout() efService_Console { return efService_Console{m_log: func(message string) efEffect[struct{}] { return func(ctx efContext) efExit[struct{}] { fmt.Println(message);return efExit[struct{}]{} } } } }\n")
	for _, p := range r.Program.Providers {
		out.WriteString("func efProvider_" + p.Name + "() efService_" + p.Service + " { return efService_" + p.Service + "{\n")
		for _, m := range p.Methods {
			out.WriteString("m_" + m.Name + ": " + strings.TrimSpace(g.function(m)) + ",\n")
		}
		out.WriteString("} }\n")
	}
	for _, f := range r.Program.Functions {
		ret := goType(f.Return)
		if f.Effect {
			ret = "efEffect[" + ret + "]"
		}
		out.WriteString("func efFunction_" + f.Name + "(" + goParams(f) + ") " + ret + " {\n")
		if f.Effect {
			out.WriteString("return func(ctx efContext) efExit[" + goType(f.Return) + "] {\n")
		}
		out.WriteString(g.block(f.Body, f.Effect, f.Return))
		if f.Effect {
			out.WriteString("}\n")
		}
		out.WriteString("}\n")
	}
	out.WriteString("func main() { exit:=efFunction_main()(efContext{});if exit.failure!=nil {fmt.Fprintln(os.Stderr,exit.failure.tag);os.Exit(1)};if exit.defect!=nil {fmt.Fprintln(os.Stderr,\"defect:\",exit.defect);os.Exit(1)}\n")
	if r.Find("main").Contract.Success != "()" {
		out.WriteString("fmt.Println(exit.value)\n")
	}
	out.WriteString("}\n")
	formatted, err := format.Source([]byte(out.String()))
	if err != nil {
		return "", fmt.Errorf("Go lowering generated invalid syntax: %w", err)
	}
	return string(formatted), nil
}
func (g *goEmitter) function(f *Function) string {
	ret := goType(f.Return)
	if f.Effect {
		ret = "efEffect[" + ret + "]"
	}
	open := "func(" + goParams(f) + ") " + ret + " {\n"
	close := "}\n"
	if f.Effect {
		open += "return func(ctx efContext) efExit[" + goType(f.Return) + "] {\n"
		close = "}\n}\n"
	}
	return open + g.block(f.Body, f.Effect, f.Return) + close
}
func (g *goEmitter) failed(name, ret string) string {
	return "if " + name + ".failure != nil || " + name + ".defect != nil { return efExit[" + goType(ret) + "]{failure:" + name + ".failure,defect:" + name + ".defect} }\n"
}
func (g *goEmitter) block(b *Block, effect bool, ret string) string {
	var out strings.Builder
	finish := func(expr string) {
		if effect {
			out.WriteString("return efExit[" + goType(ret) + "]{value:" + expr + "}\n")
		} else {
			out.WriteString("return " + expr + "\n")
		}
	}
	if len(b.Statements) == 0 {
		finish("struct{}{}")
		return out.String()
	}
	for i, s := range b.Statements {
		if s.Kind == "fail" {
			out.WriteString("return efExit[" + goType(ret) + "]{failure:&efFailure{tag:" + strconv.Quote(s.Name) + "}}\n")
			continue
		}
		expr := g.expr(s.Value, effect, ret, &out)
		if s.Kind == "let" {
			out.WriteString("efLocal_" + s.Name + " := " + expr + "\n_ = efLocal_" + s.Name + "\n")
			if i == len(b.Statements)-1 {
				finish("struct{}{}")
			}
		} else if i == len(b.Statements)-1 {
			if s.Value.Type.Success == "never" {
				out.WriteString("_ = " + expr + "\nreturn efExit[" + goType(ret) + "]{defect:fmt.Errorf(\"bottom expression unexpectedly succeeded\")}\n")
			} else {
				finish(expr)
			}
		} else {
			out.WriteString("_ = " + expr + "\n")
		}
	}
	return out.String()
}
func (g *goEmitter) expr(e *Expr, effect bool, ret string, out *strings.Builder) string {
	switch e.Kind {
	case "string":
		return strconv.Quote(e.Text)
	case "bool":
		return e.Text
	case "unit":
		return "struct{}{}"
	case "name":
		if e.Text == "provider" {
			return "efProvider_" + e.Name + "()"
		}
		return "efLocal_" + e.Name
	case "call":
		args := []string{}
		for _, a := range e.Args {
			expr := g.expr(a, effect, ret, out)
			name := g.temp()
			out.WriteString(name + " := " + expr + "\n")
			args = append(args, name)
		}
		if e.Left.Kind == "name" {
			return "efFunction_" + e.Left.Name + "(" + strings.Join(args, ", ") + ")"
		}
		return "efCall_" + e.Left.Left.Name + "_" + e.Left.Name + "(" + strings.Join(args, ", ") + ")"
	case "run":
		expr := g.expr(e.Left, effect, ret, out)
		name := g.temp()
		out.WriteString(name + " := " + expr + "(ctx)\n" + g.failed(name, ret))
		return name + ".value"
	case "provide":
		left := g.expr(e.Left, effect, ret, out)
		name := g.temp()
		out.WriteString(name + " := " + left + "\n")
		right := g.expr(e.Right, effect, ret, out)
		return "efProvide_" + e.Name + "(" + name + ", " + right + ")"
	case "catch":
		left := g.expr(e.Left, effect, ret, out)
		var fallback strings.Builder
		right := g.expr(e.Right, false, e.Type.Success, &fallback)
		return "efCatch(" + left + ", " + strconv.Quote(e.Name) + ", func() " + goType(e.Type.Success) + " {\n" + fallback.String() + "return " + right + "\n})"
	case "binary":
		left := g.expr(e.Left, effect, ret, out)
		name := g.temp()
		out.WriteString(name + " := " + left + "\n")
		right := g.expr(e.Right, effect, ret, out)
		return "(" + name + " " + e.Name + " " + right + ")"
	case "if":
		var body strings.Builder
		condition := g.expr(e.Left, effect, e.Type.Success, &body)
		body.WriteString("if " + condition + " {\n" + g.block(e.Then, effect, e.Type.Success) + "} else {\n" + g.block(e.Else, effect, e.Type.Success) + "}\n")
		if effect {
			name := g.temp()
			out.WriteString(name + " := func() efExit[" + goType(e.Type.Success) + "] {\n" + body.String() + "}()\n" + g.failed(name, ret))
			return name + ".value"
		}
		return "func() " + goType(e.Type.Success) + " {\n" + body.String() + "}()"
	}
	panic("unchecked expression reached Go emitter")
}
