package main

import (
	"bytes"
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"effra.local/prototype/internal/compiler"
	"effra.local/prototype/internal/receipt"
	rt "effra.local/prototype/runtime/effra"
)

// sizeFixture is one row of the size-conformance matrix in
// conformance/size/fixtures. The deterministic retention facts are checked
// here, in the gate; byte comparisons against the Go and TypeScript/Effect
// controls belong to the matrix in conformance/size/matrix.
type sizeFixture struct {
	name    string
	modules []rt.RuntimeModule
	// absent packages appear neither in the transitive dependencies nor in
	// the executable's symbol table; present packages appear in both.
	absent  []string
	present []string
	// output is the program's stdout on both targets; empty means build only.
	output string
}

var platformPackages = []string{"net", "net/http", "crypto/tls", "encoding/json", "os/exec"}

var sizeFixtures = []sizeFixture{
	{name: "minimal", modules: []rt.RuntimeModule{rt.RuntimeModuleCore}, absent: platformPackages, output: "minimal\n"},
	{name: "minimal-unused", modules: []rt.RuntimeModule{rt.RuntimeModuleCore}, absent: platformPackages, output: "minimal\n"},
	{name: "managed", modules: []rt.RuntimeModule{rt.RuntimeModuleCore}, absent: platformPackages, output: "child joined; interrupted; timed out; recovered\n"},
	{name: "codec", modules: []rt.RuntimeModule{rt.RuntimeModuleCodec, rt.RuntimeModuleCore}, absent: []string{"net", "net/http", "crypto/tls", "os/exec"}, output: "{\"id\":\"7\",\"name\":\"Ada\"}\n"},
	// The HTTP row is the detector's negative control: the same receipt
	// fields that stay empty above must name the transport here.
	{name: "http", modules: []rt.RuntimeModule{rt.RuntimeModuleCore, rt.RuntimeModuleHTTP}, absent: []string{"os/exec"}, present: []string{"net", "net/http"}},
	{name: "direct", modules: []rt.RuntimeModule{rt.RuntimeModuleCore}, absent: platformPackages, output: "Hello, <ada!>\n"},
	{name: "pipe", modules: []rt.RuntimeModule{rt.RuntimeModuleCore}, absent: platformPackages, output: "Hello, <ada!>\n"},
}

type builtSize struct {
	native receipt.Application
	js     receipt.Application
	module []byte
}

func readReceipt(t *testing.T, path string) receipt.Application {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	var measured receipt.Application
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&measured); err != nil {
		t.Fatalf("%s: %v", path, err)
	}
	if measured.Schema != receipt.Schema {
		t.Fatalf("%s: schema %q", path, measured.Schema)
	}
	return measured
}

func symbolPackages(measured receipt.Application) map[string]receipt.SymbolPackage {
	packages := map[string]receipt.SymbolPackage{}
	for _, entry := range measured.Symbols.Packages {
		packages[entry.Package] = entry
	}
	return packages
}

// withoutHeader drops the generated header line, which names the source
// revision and is the only text two equivalent sources may differ in.
func withoutHeader(t *testing.T, module []byte) []byte {
	t.Helper()
	header, rest, found := bytes.Cut(module, []byte("\n"))
	if !found || !bytes.HasPrefix(header, []byte("// Generated by the Effra prototype. Source revision: ")) {
		t.Fatalf("unexpected generated header %q", header)
	}
	return rest
}

func TestSizeFixturesRetainOnlyReachableRuntime(t *testing.T) {
	binary := buildTestCLI(t)
	root := t.TempDir()
	fixtures, err := filepath.Abs(filepath.Join("..", "..", "conformance", "size", "fixtures"))
	if err != nil {
		t.Fatal(err)
	}
	modules, err := filepath.Abs(filepath.Join("..", "..", "node_modules"))
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(modules, filepath.Join(root, "node_modules")); err != nil {
		t.Fatal(err)
	}
	built := map[string]builtSize{}
	for _, fixture := range sizeFixtures {
		source := filepath.Join(fixtures, fixture.name+".ef")
		native := filepath.Join(root, "receipts", fixture.name+".go.json")
		executable := filepath.Join(root, "bin", fixture.name)
		if stdout, stderr, code := runTestCLIDir(t, binary, root, "", "build", source, "-o", executable, "--receipt", native); code != 0 {
			t.Fatalf("%s: go build failed: code=%d stdout=%q stderr=%q", fixture.name, code, stdout, stderr)
		}
		script := filepath.Join(root, "js", fixture.name+".mjs")
		module := filepath.Join(root, "receipts", fixture.name+".js.json")
		if stdout, stderr, code := runTestCLIDir(t, binary, root, "", "build", source, "--target", "js", "--entry", "-o", script, "--receipt", module); code != 0 {
			t.Fatalf("%s: js build failed: code=%d stdout=%q stderr=%q", fixture.name, code, stdout, stderr)
		}
		emitted, err := os.ReadFile(script)
		if err != nil {
			t.Fatal(err)
		}
		row := builtSize{native: readReceipt(t, native), js: readReceipt(t, module), module: emitted}
		built[fixture.name] = row

		measured := row.native
		if !slices.Equal(measured.Plan.RuntimeModules, fixture.modules) {
			t.Errorf("%s: runtime modules = %v, want %v", fixture.name, measured.Plan.RuntimeModules, fixture.modules)
		}
		selected, err := rt.SelectSources(fixture.modules...)
		if err != nil {
			t.Fatal(err)
		}
		runtimeFiles := []string{}
		for _, file := range measured.Generation.Files {
			if name, found := strings.CutPrefix(file.Path, "runtime/"); found {
				runtimeFiles = append(runtimeFiles, name)
				if file.Bytes != len(selected[name]) {
					t.Errorf("%s: runtime/%s has %d bytes, want %d", fixture.name, name, file.Bytes, len(selected[name]))
				}
			}
		}
		if len(runtimeFiles) != len(selected) {
			t.Errorf("%s: generated runtime files %v, want the selected %d", fixture.name, runtimeFiles, len(selected))
		}
		if measured.Compiler.RuntimeSourceBytes <= measured.Generation.RuntimeBytes && fixture.name != "http" {
			t.Errorf("%s: application runtime %d bytes is not smaller than the distributed runtime %d", fixture.name, measured.Generation.RuntimeBytes, measured.Compiler.RuntimeSourceBytes)
		}
		if info, err := os.Stat(executable); err != nil || info.Size() != measured.Binary.Bytes {
			t.Errorf("%s: receipt binary bytes %d do not match the executable (%v)", fixture.name, measured.Binary.Bytes, err)
		}
		symbols := symbolPackages(measured)
		for _, name := range fixture.absent {
			if slices.Contains(measured.Deps.Transitive, name) {
				t.Errorf("%s: depends on %s", fixture.name, name)
			}
			if _, found := symbols[name]; found {
				t.Errorf("%s: executable retains %s symbols", fixture.name, name)
			}
		}
		for _, name := range fixture.present {
			if !slices.Contains(measured.Deps.Transitive, name) {
				t.Errorf("%s: does not depend on %s", fixture.name, name)
			}
			if _, found := symbols[name]; !found {
				t.Errorf("%s: executable has no %s symbols", fixture.name, name)
			}
		}
		if len(measured.Deps.NonStandard) != 2 || measured.Deps.NonStandard[0] != "effra.generated" || measured.Deps.NonStandard[1] != "effra.generated/runtime" {
			t.Errorf("%s: non-standard dependencies %v", fixture.name, measured.Deps.NonStandard)
		}

		js := row.js
		if js.Mode != "entry" || len(js.Plan.RuntimeModules) != 0 || js.Module.Bytes != int64(len(emitted)) {
			t.Errorf("%s: js receipt %+v does not describe the emitted entry module", fixture.name, js.Module)
		}
		if len(js.External) == 0 || js.External[0].Specifier != "effect" || js.External[0].Dynamic {
			t.Errorf("%s: js external runtime %+v does not name effect statically", fixture.name, js.External)
		}
		hostHTTP := slices.ContainsFunc(js.External, func(link compiler.JSImport) bool { return link.Specifier == "node:http" && link.Dynamic })
		if hostHTTP != (fixture.name == "http") {
			t.Errorf("%s: js node:http link = %v: %+v", fixture.name, hostHTTP, js.External)
		}

		if fixture.output == "" {
			continue
		}
		if output, err := exec.Command(executable).Output(); err != nil || string(output) != fixture.output {
			t.Errorf("%s: native output %q (%v), want %q", fixture.name, output, err, fixture.output)
		}
		if output, err := exec.Command("node", script).Output(); err != nil || string(output) != fixture.output {
			t.Errorf("%s: js output %q (%v), want %q", fixture.name, output, err, fixture.output)
		}
	}

	// The HTTP transport is visible to every detector the minimal rows use.
	if minimal, transport := symbolPackages(built["minimal"].native)["effra.generated/runtime"], symbolPackages(built["http"].native)["effra.generated/runtime"]; transport.TextBytes <= minimal.TextBytes {
		t.Errorf("HTTP runtime symbols (%d text bytes) do not exceed the minimal core (%d)", transport.TextBytes, minimal.TextBytes)
	}

	// Unused declarations and equivalent spellings retain exactly the same
	// program: identical runtime, imports, dependencies, symbol table and
	// executable size natively, and an identical module in JavaScript.
	for _, pair := range [][2]string{{"minimal", "minimal-unused"}, {"direct", "pipe"}} {
		a, b := built[pair[0]], built[pair[1]]
		runtimeOnly := func(files []receipt.File) []receipt.File {
			return slices.DeleteFunc(slices.Clone(files), func(file receipt.File) bool { return !strings.HasPrefix(file.Path, "runtime/") })
		}
		if !slices.Equal(runtimeOnly(a.native.Generation.Files), runtimeOnly(b.native.Generation.Files)) {
			t.Errorf("%s/%s: generated runtime differs", pair[0], pair[1])
		}
		if a.native.Generation.MainBytes != b.native.Generation.MainBytes {
			t.Errorf("%s/%s: generated main %d vs %d bytes", pair[0], pair[1], a.native.Generation.MainBytes, b.native.Generation.MainBytes)
		}
		for pkg, imports := range a.native.Imports {
			if !slices.Equal(imports, b.native.Imports[pkg]) {
				t.Errorf("%s/%s: %s imports %v vs %v", pair[0], pair[1], pkg, imports, b.native.Imports[pkg])
			}
		}
		if !slices.Equal(a.native.Deps.Transitive, b.native.Deps.Transitive) {
			t.Errorf("%s/%s: dependencies differ", pair[0], pair[1])
		}
		if a.native.Symbols.ListingSHA256 != b.native.Symbols.ListingSHA256 || a.native.Binary.Bytes != b.native.Binary.Bytes {
			t.Errorf("%s/%s: executables differ: symbols %s vs %s, %d vs %d bytes", pair[0], pair[1], a.native.Symbols.ListingSHA256, b.native.Symbols.ListingSHA256, a.native.Binary.Bytes, b.native.Binary.Bytes)
		}
		if !bytes.Equal(withoutHeader(t, a.module), withoutHeader(t, b.module)) {
			t.Errorf("%s/%s: emitted JavaScript differs", pair[0], pair[1])
		}
	}
}
